package model.staticvo;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Feb 04 18:16:45 ECT 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class StaticGenderViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public StaticGenderViewImpl() {
    }
}

